# This is a basic workflow to help you get started with Actions

name: testWorkflow


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a simple script
      run: |
        echo "Running on ${{ github.actor }}'s subdomain"
