# This is a basic workflow to help you get started with Actions

name: testWorkflow


on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
